sonar.projectKey=mohammad-arslan_sis
sonar.organization=mohammad-arslan

sonar.sources=app
sonar.tests=tests

sonar.exclusions=vendor/**,storage/**,node_modules/**,public/**
sonar.sourceEncoding=UTF-8
