sonar.projectKey=Mohammad-Arslan_sis
sonar.organization=mohammad-arslan

sonar.sources=app
sonar.tests=tests

sonar.exclusions=vendor/**,storage/**,node_modules/**,public/**,bootstrap/cache/**,database/migrations/**,database/seeders/**,resources/lang/**,resources/views/**,routes/**,config/**,*.blade.php,**/*.min.js,**/*.min.css,**/*.map,coverage/**,.git/**,.github/**,phpunit.xml,.env.example,database/factories/**
sonar.sourceEncoding=UTF-8
